import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Input';
import Modal from '@/components/Modal';
import Table from '@/components/Table';
import Flex from '@/components/Flex';

import ProductListFilters from '@/features/product/components/ProductListFilters';

import type { PageProps, SearchParams } from '@/typings';

import { formatPhoneNumber } from '@/utils/text';
import { parseSearchParams as psp } from '@/utils/actions/search-params';

import { productGetAll } from '@/features/product/routes';

export const metadata: Metadata = {
    title: 'Админпанель | Товары',
    description: 'Generated by create next app',
};

const columns = [
    {
        title: 'ID',
        name: 'id',
    },
    {
        title: 'Название',
        name: 'name',
    },
    {
        title: 'Стоимость',
        name: 'price',
    },
];

const getProducts = async (params?: SearchParams) => {
    const response = await productGetAll({
        page: psp.integer(params?.page) || 1,
        productId: psp.integer(params?.productId),
        name: psp.string(params?.name),
    });
    if (!response.isSuccess) {
        throw new Error('Ошибка при загрузке страницы');
    }

    return response.data;
};

export default async function Product(props: PageProps) {
    const products = await getProducts(props.searchParams);

    return (
        <main>
            <Container className="mt-lg">
                <ProductListFilters />
                <Table columns={columns} data={products} />
            </Container>
        </main>
    );
}
