import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Input';
import Modal from '@/components/Modal';
import InputNumber from '@/components/form/InputNumber';
import Flex from '@/components/Flex';

import TextBlock from '@/widgets/TextBlock/TextBlock';

export const metadata: Metadata = {
    title: 'Часто задаваемые вопросы',
    description: 'Generated by create next app',
};
export default function Contacts() {
    return (
        <main>
            <TextBlock
                title="How can we help you?"
                content="Search our FAQ and find your answers"
                after={<Input placeholder="Search" />}
            />

            <TextBlock
                title="Still looking for an answer?"
                content="Shoot our team an email and we’ll get back to you ASAP (definitely within 24 hours)"
                after={<Button>Send an email</Button>}
            />
        </main>
    );
}
