import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Field';
import Modal from '@/components/Modal';
import Table from '@/components/Table';
import Flex from '@/components/Flex';
import { formatPhoneNumber } from '@/utils/text';

export const metadata: Metadata = {
    title: 'Админпанель | Пользователи',
    description: 'Generated by create next app',
};

const columns = [
    {
        title: 'ID',
        name: 'id',
    },
    {
        title: 'Email',
        name: 'email',
    },
    {
        title: 'Телефон',
        name: 'phone',
        render: formatPhoneNumber,
    },
    {
        title: 'ФИО',
        name: 'fio',
    },
];

const data = [
    {
        id: 34,
        email: null,
        phone: '79090023791',
        fio: 'Никита Павлович',
    },
    {
        id: 34,
        email: null,
        phone: '79090023791',
        fio: 'Никита Павлович',
    },
];

export default function Users() {
    return (
        <main>
            <Container>
                <Table columns={columns} data={data} />
            </Container>
        </main>
    );
}
