import Image from 'next/image';
import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/Tooltip';
import { FaBeer } from 'react-icons/fa';
import styles from './page.module.css';
import type { Metadata } from 'next';
import TextBlock from '@/widgets/TextBlock/TextBlock';
import Input from '@/components/form/Field';
import Modal from '@/components/Modal';
import InputNumber from '@/components/form/InputNumber';

import ProductPrice from '@/features/product/components/ProductPrice';

export const metadata: Metadata = {
    title: 'Моя первая страница',
    description: 'Generated by create next app',
};

const product = {
    title: '123',
    description: 'dsfsfsd',
    id: 4325,
    rating: 4.3,
    price: 99.99,
    prevPrice: 125,
    discount: 20.2,
    advantages: [
        {
            title: '',
            description: '',
        },
        {
            title: '',
            description: '',
        },
    ],
};

export default function Home() {
    return (
        <main>
            <Container>
                <Row>
                    <Col md={7}>{/* <ProductImage/> */}</Col>
                    <Col md={5}>
                        <div>
                            <Title level={1}>{product.title}</Title>
                            {/* <Rating
                                value={rating}
                                readonly
                            /> */}
                            <ProductPrice
                                price={product.price}
                                prevPrice={product.prevPrice}
                                discount={product.discount}
                            />
                            {/* <ProductAddButton/> */}
                            <Paragraph>{product.description}</Paragraph>
                            {/* <AdvantagesList advantages={advantages} /> */}
                        </div>
                    </Col>
                </Row>
            </Container>

            {/* <ProductCharacterisctsi/> */}

            {/* Product */}
        </main>
    );
}
