import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Field';
import Modal from '@/components/Modal';
import Table from '@/components/Table';
import Flex from '@/components/Flex';

import OrdersListFilters from '@/features/order/components/OrderListFilters';

import type { PageProps, SearchParams } from '@/typings';

import { formatPhoneNumber } from '@/utils/text';
import { parseSearchParams as psp } from '@/utils/actions/search-params';

import { orderGetAll } from '@/features/order/routes';

export const metadata: Metadata = {
    title: 'Админпанель | Заказы',
    description: 'Generated by create next app',
};

const columns = [
    {
        title: 'ID',
        name: 'id',
    },
    {
        title: 'Заказчик',
        name: 'fio',
        render: (fio: string) => <Link>{fio}</Link>,
    },
    {
        title: 'Статус',
        name: 'status',
    },
    {
        title: 'Сумма',
        name: 'total',
    },
];

const getOrders = async (params?: SearchParams) => {
    const response = await orderGetAll({
        page: psp.integer(params?.page) || 1,
        orderId: psp.integer(params?.orderId),
    });
    if (!response.isSuccess) {
        throw new Error('Ошибка при загрузке страницы');
    }

    return response.data;
};

export default async function Order(props: PageProps) {
    const orders = await getOrders(props.searchParams);

    return (
        <main>
            <Container className="mt-lg">
                <OrdersListFilters />
                <Table columns={columns} data={orders} />
            </Container>
        </main>
    );
}
