export const SHOP_INFO = {
    NAME: '',
    INN: '',
    OGRN: '',
    PHONE: '',
    EMAIL: '',
};

export const DELIVERY_INFO = {
    BOXBERRY_SENDER_POINT_ID: 1,
    CDEK_SENDER_POINT_ID: 1,
    DELLIN_SENDER_POINT_ID: 1,
};

export const ORDER_STATUS = {
    PAYMENT: 'PAYMENT',
    PREPARATION: 'PREPARATION',
    DELIVERY: 'DELIVERY',
    WAITING: 'WAITING',
    RECEIVED: 'RECEIVED',
};

export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    SUCCEEDED: 'SUCCEEDED',
    CANCELED: 'CANCELED',
};

export const USER_ROLE = {
    USER: 'USER',
    ADMIN: 'ADMIN',
    GUEST: 'GUEST',
};

export const USER_SEX = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
};

export const DELIVERY_COMPANY = {
    BOXBERRY: 'BOXBERRY',
    CDEK: 'CDEK',
    DELLIN: 'DELLIN',
    FIVEPOST: 'FIVEPOST',
};

export const DELIVERY_TYPE = {
    COURIER: 'COURIER',
    POINT: 'POINT',
};

export const PAYMENT_TYPE = {
    BANK_CARD: 'BANK_CARD',
    SBP: 'SBP',
};

export const MEASURE_TYPE = {
    PIECE: 'PIECE',
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    TON: 'TON',
    CENTIMETER: 'CENTIMETER',
    DECIMETER: 'DECIMETER',
    METER: 'METER',
    SQURE_CENTIMETER: 'SQURE_CENTIMETER',
    SQURE_DECIMETER: 'SQURE_DECIMETER',
    SQURE_METER: 'SQURE_METER',
    MILLILITER: 'MILLILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    KILOWATT_HOUR: 'KILOWATT_HOUR',
    GIGACALORIE: 'GIGACALORIE',
    DAY: 'DAY',
    HOUR: 'HOUR',
    MINUTE: 'MINUTE',
    SECOND: 'SECOND',
    KILOBYTE: 'KILOBYTE',
    MEGABYTE: 'MEGABYTE',
    GIGABYTE: 'GIGABYTE',
    TERABYTE: 'TERABYTE',
    ANOTHER: 'ANOTHER',
};
