import { useMemo } from 'react';
import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/Tooltip';
import TextBlock from '@/widgets/TextBlock/TextBlock';
import Input from '@/components/form/Field';
import Modal from '@/components/Modal';
import InputNumber from '@/components/form/InputNumber';
import Flex from '@/components/Flex';
import Breadcrumbs from '@/components/Breadcrumbs';

import BasketList from '@/features/basket/components/BasketList';
import BasketTotalResult from '@/features/basket/components/BasketTotalResult';

import { basketCalcTotalResult } from '@/features/basket/utils/basketCalcTotalResult';

import styles from './page.module.css';

const products = [
    {
        id: 1,
        name: 'Мистическое яйцо динозавра',
        price: 999,
        discount: 20,
        images: ['https://dummyimage.com/800x800/f4eee0/ab7c0d&text=1'],
        rating: 4.8,
    },
];

export const metadata: Metadata = {
    title: 'Моя корзина',
    description: 'Generated by create next app',
};

export default function Basket() {
    const totalResult = useMemo(() => basketCalcTotalResult(products), [products]);

    return (
        <main>
            <Container>
                <Title level={1}>Корзина</Title>
                {/* TODO
                <Banner
                    title="The papier promise"
                    content="if you are not 100% happy"
                /> */}
                <Row>
                    <Col md={9}>
                        <BasketList products={products} />
                    </Col>
                    <Col md={3}>
                        <BasketTotalResult result={totalResult} />
                    </Col>
                </Row>
            </Container>
        </main>
    );
}
