import type { Metadata } from 'next';
import { plexSans } from '@/ui/fonts';
import '../styles/index.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={plexSans.className}>{children}</body>
        </html>
    );
}
